# Generated by Django 4.1.6 on 2023-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=225)),
                ('technologies_used', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=50)),
                ('challenges', models.CharField(max_length=255)),
                ('results_learnings', models.CharField(max_length=255)),
                ('start_timeline', models.DateField()),
                ('end_timeline', models.DateField()),
                ('post_date', models.DateTimeField()),
                ('project_link', models.CharField(max_length=255)),
            ],
        ),
    ]
