# Generated by Django 5.0.2 on 2024-06-28 10:04

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projectinfo_image2_projectinfo_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=250)),
                ('part_1', models.CharField(max_length=50)),
                ('part_2', models.CharField(blank=True, max_length=250, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
