# Generated by Django 5.0.2 on 2024-08-25 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_projectinfo_challenges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='part_1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='part_2',
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.blogs')),
            ],
        ),
    ]
