# Generated by Django 5.0.7 on 2026-03-19 18:53

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blogs_intro_remove_blogs_part_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=150)),
                ('date_earned', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='results_learnings',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='subheading',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='end_timeline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.GetFileName)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.projectinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
