# Generated by Django 5.0.7 on 2026-04-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_certification_alter_blogsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='section_type',
            field=models.CharField(choices=[('feature', 'Key Feature'), ('gallery', 'Gallery Image'), ('other', 'Other')], default='feature', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
